@url = http://localhost:3000/
###

GET {{url}}islas
Content-Type: application/json

{
    "datos": [
        [1, 1, 0, 1, 1],
        [1, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 1, 0, 0, 1],
        [1, 1, 0, 1, 1]
    ]
}
###